api_key: "XXXXXXXXXXX"
HPC keywords:
  [
    "high performance computing",
    "high-performance computing",
    "high performance computer",
    "supercomputer*",
    "supercomputing",

  ]

Healthcare keywords:
  [
    "healthcare",
    "health" ,
    "clinic*",
    "Medicine",
    "disease*",
    "Medication",
    "pharmaceutical",
    "Medical",
    "patient*",
    "diagnosis",
    "diagnostic",
    "drug",
    "treatment",
    "surgery",
    "genomics",
    "health care",
    "genes",
    "genetics",
    "biomedical",
    "pathology" ,
    "public health",
    "neuroimaging ",
    "epidemiology",
    "genome",
    "therapy",

  ] 
publication_list_path: "./data/2019-abs-ri-journal-list.csv"
save_dir: "./save"


